### ISSUE TITLE
Anton Stankowski – Quadratspirale schwarz

### ISSUE THREAD

**Issue by gkaramanis** [sharlagelfand/RecreationThursday#3]
Anton Stankowski
Quadratspirale schwarz, 1952
https://www.artsy.net/artwork/anton-stankowski-quadratspirale-schwarz

Georgios Karamanis
@geokaramanis

Any help with the alt-text would be appreciated!

**Comment by Ijeamakaanyene** [comment]
Yay! This piece is really cool. 

Would you be okay with August 1st as your curation date? Would you also be down to be the curator, i.e. announce it on twitter?

**Comment by gkaramanis** [comment]
Yes, it would be an honor! 😀

**Comment by Ijeamakaanyene** [comment]
Amazing! I'll add you to the readme as the curator for that date. And I'll loop back in a week or so with a first draft for the alt-text!

**Comment by gkaramanis** [comment]
Sounds great!

**Comment by Ijeamakaanyene** [comment]
Hey! So excited for you to curate this Thursday!

Below is the alt text draft - feel free to modify and let us know! On Wednesday-ish I'll update the README with your piece and the link to the alt text. 

Anton Stankowkski, Quadratspirale schwarz, 1952
This is a silkscreen print of multiple squares with a thick black border. The fill of each square is the same color as the piece's off-white background. Starting from the center of the print, the squares start to form a spiral traveling counterclockwise. As the spiral grows, the squares decrease in size.

**Comment by gkaramanis** [comment]
I’m excited, too! The alt text looks perfect, nothing to change!

Is there anything else I should know or do before posting on Thursday?

**Comment by Ijeamakaanyene** [comment]
Nope!  You are all good.

I will update the main README with all the information by Wednesday and on that day I'll also close this issue! 

On Thursday, feel free to include what you think is best in the post. I think its most important to include 1) the hashtag lol, 2) The name and the artists, and 3) a reminder that they can recreate or remix using any medium they want. Some nice to haves are: 1) Why did you choose this particular piece of art? and 2) The link to the repo.

**Comment by Ijeamakaanyene** [comment]
So excited to see your curator post tomorrow!

**Comment by MilesOtt** [comment]
yay! I posted! Thanks for your help @Ijeamakaanyene !!!
