### ISSUE TITLE
Question: scope for submissions

### ISSUE THREAD

**Issue by matt-dray** [sharlagelfand/RecreationThursday#5]
To what extent does the piece need to be 'art' versus 'a design'?

For example, would textile patterns like the [PDX airport carpet](https://en.wikipedia.org/wiki/Portland_International_Airport_carpet) (SRG Partnership, 1987) be acceptable? (Other, less hipster, textiles are available.)

**Comment by Ijeamakaanyene** [comment]
This is a great question! My opinion is that I think we would be happy to do a "design" versus "art" as long as there is a good quality photo of the piece online people can inspect, the piece can be directly attributable to someone, and is a design that feasibly can be reproduced.

**Comment by Ijeamakaanyene** [comment]
Hey! Going to close this issue for now. Feel free to open a new one if you'd like to curate!
