### ISSUE TITLE
Design for Wrapping-paper: De Bijenkorf

### ISSUE THREAD

**Issue by jiwanheo** [sharlagelfand/RecreationThursday#7]
Hello! I'd like to submit this piece by M.C. Escher.

This is a little different than the previous ones, in that there's texts involved. If you think this is not suitable, please let me know!

I'll try my best with the alt-text, but I'd love to get some help!

https://mcescher.com/wp-content/uploads/2019/05/LW-232.jpg
https://www.wikiart.org/en/m-c-escher/not_detected_204690

![image](https://user-images.githubusercontent.com/30027508/133847542-4a793de3-7708-4f25-b995-aa1970bc5483.png)

**Comment by Ijeamakaanyene** [comment]
So sorry about the delay on this! Sharla and I have been swamped. We'd love to have you as a curator. Its definitely complicated because text is involved - but lets give it a shot! Would this Thursday be okay or is the turn around time too tight?

**Comment by jiwanheo** [comment]
No problem, it gave me some time to get a head start. (Not quite done yet, but it doesn't look too hard!)

I think I can do tomorrow! I'll try to get my recreation (and alt-text) finished today, so people have some starting point

**Comment by jiwanheo** [comment]
Alt text:

Design for wrapping paper: De Bijenkorf (1933) is a rectangular design pattern that is ink stamped on laid paper using carved woodcut block. The title has the meaning of "the beehives" in Dutch. This 11 letter sequence is broken up into 2 consecutive letter intervals, which are used as one of many tiles that make up the output that resembles a grid. Each tile either spells a 2 letter sequence, or draws a semi circle. The background colour alternates between black and ivory, while the letters or semi circles are coloured with the opposite, and are rotated randomly in 90 degree intervals.

Also my code (100 lines or so!)
https://github.com/jiwanheo/RecreationThursday/blob/main/week08/code.Rmd

Let me know what you think, I'll wait for the go ahead!

**Comment by Ijeamakaanyene** [comment]
This looks great. I'll update the README! You are down to announce tomorrow, yes? Also as a side note, just in case you want to curate in the future. You do not have to recreate before your date goes live - but its exciting that you did!

**Comment by Ijeamakaanyene** [comment]
I am also screaming about ggfittext I wish I knew about it a couple months ago, when I was working on a manuscript haha

**Comment by jiwanheo** [comment]
Yup, I'll announce tomorrow! Excited to finally contribute :)
